<div id="wrapper" >
    <div id="banner" align="center">
        <h1>Welcome to the World</h1>
	 <div id="clock"></div>
	 <div id="search">
	<form method="post" action="search_results.php" autocomplete="off">
	<input type="text" name="searchterm">
	<input type="submit" value="Search">
	</form>
	</div>
    
	<div class="dropdown">
     <button class="dropbtn">Make a Review</button>
     <div class="dropdown-content">
     <a href="gf.php">General Feedback</a>
	 <a href="gf.php">Technical Complain</a>
     <a href="gf.php">Others</a>
  </div>
  </div>
  </div>
    <div id="nav">
	 <a href="index.php">Home</a>
	 <a href="show_nations.php">Nations</a>
	 <a href="show_regions.php">Regions</a>
	 <a href="show_continents.php">Continents</a>
	 <a href="show_oceans.php">Oceans and Seas</a>
	 <a href="show_places_interest.php">Places of Interest</a>
	 <a href="show_links.php">Links</a>
	 <a href="login.php">log in</a>
	 <button onclick="popUp()">Add Nation</button>
</div>

